import type {
  OrderItem,
  VehicleAsset,
  TripPlan,
  DockManifestItem,
  UserAccount,
  MetricStat,
} from "./types";

export const MOCK_USERS: Record<string, UserAccount> = {
  dispatcher: {
    username: "dispatcher",
    name: "Sarath Gunawardena",
    role: "Dispatcher",
    initials: "SG",
    location: "Peliyagoda Planning Office",
  },
  loader: {
    username: "loader",
    name: "Sunil Jayasinghe",
    role: "Loader",
    initials: "SJ",
    location: "Peliyagoda Loading Dock Bay 3",
  },
  driver: {
    username: "driver",
    name: "Nimal Fernando",
    role: "Driver",
    initials: "NF",
    location: "Reefer Truck VEH001 · Colombo",
  },
  store_manager: {
    username: "store_manager",
    name: "Anura Silva",
    role: "Store Manager",
    initials: "AS",
    location: "Waypoint Fresh OUT001 · Colombo Central",
  },
};

export const MOCK_DISPATCH_METRICS: MetricStat[] = [
  {
    label: "Confirmed Orders",
    value: "148",
    trend: { direction: "up", label: "+12% vs yesterday" },
    note: "14 Pending Cutoff Review",
    tone: "yellow",
    bars: [30, 45, 60, 55, 75, 90, 85],
  },
  {
    label: "Active Vehicles",
    value: "18 / 22",
    trend: { direction: "up", label: "81% Utilization" },
    note: "14 Reefer · 4 Ambient",
    tone: "blue",
    bars: [60, 65, 70, 75, 80, 85, 81],
  },
  {
    label: "Weekly Fuel Quota",
    value: "68%",
    trend: { direction: "neutral", label: "Within Target" },
    note: "4 Vehicles at High Usage",
    tone: "green",
    bars: [80, 75, 72, 70, 69, 68, 68],
  },
  {
    label: "Deferrals & Exceptions",
    value: "3",
    trend: { direction: "down", label: "-2 resolved" },
    note: "1 Multi-Skip Priority OUT003",
    tone: "red",
    bars: [8, 6, 5, 4, 4, 3, 3],
  },
];

export const MOCK_ORDERS: OrderItem[] = [
  {
    id: "ord-1",
    orderNumber: "ORD-2026-001",
    storeName: "Waypoint Fresh · Colombo Central (OUT001)",
    brand: "Waypoint Fresh",
    temp: "chilled",
    cartons: 42,
    weightKg: 480,
    volumeM3: 2.8,
    deliveryDate: "2026-09-30",
    status: "Planned",
    isAfterCutoff: false,
    assignedTripId: "TRIP-COL-01",
  },
  {
    id: "ord-2",
    orderNumber: "ORD-2026-002",
    storeName: "Waypoint Fresh · Colombo Central (OUT001)",
    brand: "Waypoint Fresh",
    temp: "ambient",
    cartons: 85,
    weightKg: 620,
    volumeM3: 4.1,
    deliveryDate: "2026-09-30",
    status: "Planned",
    isAfterCutoff: false,
    assignedTripId: "TRIP-COL-01",
  },
  {
    id: "ord-3",
    orderNumber: "ORD-2026-003",
    storeName: "Waypoint Style · Kandy City Centre (OUT004)",
    brand: "Waypoint Style",
    temp: "ambient",
    cartons: 64,
    weightKg: 310,
    volumeM3: 5.2,
    deliveryDate: "2026-09-30",
    status: "Confirmed",
    isAfterCutoff: false,
  },
  {
    id: "ord-4",
    orderNumber: "ORD-2026-004",
    storeName: "Waypoint Tech · Liberty Plaza (OUT007)",
    brand: "Waypoint Tech",
    temp: "ambient",
    cartons: 28,
    weightKg: 520,
    volumeM3: 3.4,
    deliveryDate: "2026-09-30",
    status: "InTransit",
    isAfterCutoff: false,
    assignedTripId: "TRIP-COL-02",
  },
  {
    id: "ord-5",
    orderNumber: "ORD-2026-005",
    storeName: "Waypoint Fresh · Negombo Seaside (OUT003)",
    brand: "Waypoint Fresh",
    temp: "chilled",
    cartons: 38,
    weightKg: 410,
    volumeM3: 2.5,
    deliveryDate: "2026-09-30",
    status: "Deferred",
    priorityBoost: true,
    isAfterCutoff: true,
  },
];

export const MOCK_VEHICLES: VehicleAsset[] = [
  {
    id: "veh-1",
    plateNumber: "VEH001",
    model: "Isuzu Forward Reefer 5T",
    homeDepot: "Peliyagoda Distribution Center",
    type: "truck",
    isReefer: true,
    maxWeightKg: 5000,
    maxVolumeM3: 22,
    currentWeightKg: 3850,
    currentVolumeM3: 17.5,
    weeklyFuelQuotaLiters: 450,
    fuelConsumedLiters: 290,
    status: "in_transit",
    driverName: "Nimal Fernando",
  },
  {
    id: "veh-2",
    plateNumber: "VEH002",
    model: "Hino 300 Ambient Box 3.5T",
    homeDepot: "Peliyagoda Distribution Center",
    type: "truck",
    isReefer: false,
    maxWeightKg: 3500,
    maxVolumeM3: 16,
    currentWeightKg: 2800,
    currentVolumeM3: 13.2,
    weeklyFuelQuotaLiters: 380,
    fuelConsumedLiters: 195,
    status: "in_transit",
    driverName: "Chamara Silva",
  },
  {
    id: "veh-3",
    plateNumber: "VEH003",
    model: "Toyota HiAce Van 1.2T",
    homeDepot: "Kandy Regional Hub",
    type: "van",
    isReefer: false,
    maxWeightKg: 1200,
    maxVolumeM3: 7.5,
    currentWeightKg: 780,
    currentVolumeM3: 4.8,
    weeklyFuelQuotaLiters: 200,
    fuelConsumedLiters: 165,
    status: "available",
    driverName: "Ruwan Dias",
  },
];

export const MOCK_MANIFEST_ITEMS: DockManifestItem[] = [
  {
    id: "man-1",
    orderNumber: "ORD-2026-001",
    sku: "FRSH-DAI-001",
    description: "Farm Fresh Milk 1L Bottles (Crate of 12)",
    cartonCount: 15,
    stopSequence: 3, // Reverse sequence
    storeName: "Waypoint Fresh Colombo OUT001",
    temp: "chilled",
    checked: true,
  },
  {
    id: "man-2",
    orderNumber: "ORD-2026-001",
    sku: "FRSH-CHK-004",
    description: "Premium Poultry Chilled Breast 5kg Carton",
    cartonCount: 12,
    stopSequence: 3,
    storeName: "Waypoint Fresh Colombo OUT001",
    temp: "chilled",
    checked: true,
  },
  {
    id: "man-3",
    orderNumber: "ORD-2026-002",
    sku: "DRY-BEV-008",
    description: "Ceylon Black Tea Selected 500g Boxes (x24)",
    cartonCount: 20,
    stopSequence: 2,
    storeName: "Waypoint Fresh Negombo OUT003",
    temp: "ambient",
    checked: false,
  },
  {
    id: "man-4",
    orderNumber: "ORD-2026-003",
    sku: "STY-APP-012",
    description: "Linen Casual Shirts Assorted Sizes (Box of 30)",
    cartonCount: 18,
    stopSequence: 1,
    storeName: "Waypoint Style Kandy OUT004",
    temp: "ambient",
    checked: false,
  },
];
